### ISSUE TITLE
Ways to remove name prefix from metrics

### ISSUE THREAD

**Issue by jakeng-grabtaxi** [platinummonkey/go-concurrency-limits#170]
Hi there,

Currently all metrics are prefixed with the `name` of the limiter https://github.com/platinummonkey/go-concurrency-limits/blob/8a8cdd9b2fcac040512019a410beece161329319/core/dep.go#L31. This makes it challenging for centralising monitoring, where it would be preferable for the name to be a tag instead. 

However, I see that this function is called in quite a few places and ther isn't a good backward compatible way to remove the limiter name from the metric. One hacky way I was thinking is to change `core.PrefixMetricWithName` into a variable to allow for an external caller to override it. Do you have any suggestions (other than maintaining a private fork 😅 )?

**Comment by platinummonkey** [comment]
That seems like a reasonable change suggestion, and leave the default with it included perhaps

**Comment by jakeng-grabtaxi** [comment]
Thanks! Opened https://github.com/platinummonkey/go-concurrency-limits/pull/171.
