### ISSUE TITLE
Are the window in DefaultLimiter and the window in WindowedLimit duplicated?

### ISSUE THREAD

**Issue by mingkhuang** [platinummonkey/go-concurrency-limits#57]
As in Netflix/concurrency-limits/README.md, window is in the form of WindowedLimit. However, in your Golang version, both DefaultLimiter and WindowedLimit contain window. Are they duplicated? Thanks!

**Comment by platinummonkey** [comment]
Yes! One is a `Limit` interface (`WindowedLimit`) and the other is just the incarnation of that in the `Limiter` interface (`DefaultLimiter`). It was more for convenience.
